[mypy]
strict = True
disable_error_code = method-assign

[mypy-quark.*]
allow_redefinition = True

[mypy-examples.*]
ignore_errors = True

[mypy-quark.torch.quantization.fake_quantize.*]
allow_untyped_calls = True

[mypy-quark.torch.quantization.observer.*]
allow_untyped_calls = True
disable_error_code = override

[mypy-quark.torch.export.json_export.converter.*]
ignore_errors = True

[mypy-transformers.*]
ignore_missing_imports = True

[mypy-accelerate.*]
ignore_missing_imports = True

[mypy-tqdm.*]
ignore_missing_imports = True

[mypy-datasets.*]
ignore_missing_imports = True

[mypy-bokeh.*]
ignore_missing_imports = True

[mypy-matplotlib.*]
ignore_missing_imports = True

[mypy-rich.*]
ignore_missing_imports = True

[mypy-scipy.*]
ignore_missing_imports = True

[mypy-safetensors.*]
ignore_missing_imports = True

[mypy-quark.onnx.*]
allow_untyped_calls = True

[mypy-quark.onnxsim.*]
allow_untyped_calls = True

[mypy-onnxruntime.*]
ignore_missing_imports = True

[mypy-onnxsim.*]
ignore_missing_imports = True

[mypy-onnxruntime_extensions.*]
ignore_missing_imports = True

[mypy-quark.version.*]
ignore_missing_imports = True

[mypy-google.*]
ignore_missing_imports = True

[mypy-pandas.*]
ignore_missing_imports = True

[mypy-six.*]
ignore_missing_imports = True
