#!/usr/bin/env python3
# Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT
"""Generate teacher reasoning traces for 2-bit QAD / LoRA+KD distillation.

The QAD v6 (and LoRA+KD) recipes mix in math/reasoning traces *generated by the
BF16 teacher* so the quantized student learns the teacher's chain-of-thought.
This script produces those traces as a JSONL file in the chat ``messages``
format consumed by ``quark.torch.algorithm.qad_trainer.datasets`` (e.g. the
``reasoning_jsonl`` task in the task mix).

Model-agnostic: point ``--model_dir`` at any HF causal LM (Phi-4, QwQ-32B, ...).
GPU-shardable: run one process per GPU with distinct ``--gpu_id`` and merge the
shard files afterwards (plain ``cat``).

Examples
--------
Single GPU, OpenMath source::

    CUDA_VISIBLE_DEVICES=0 python generate_reasoning_traces.py \
        --model_dir /path/to/phi-4 --source openmath \
        --max_per_source 5000 --output /path/to/phi4_traces.jsonl

4-way shard across GPUs (2 on openmath, 2 on orca_math), then merge::

    for g in 0 1; do CUDA_VISIBLE_DEVICES=$g python generate_reasoning_traces.py \
        --gpu_id $g --num_shards 4 --source openmath --model_dir /path/to/QwQ-32B \
        --output /tmp/traces_$g.jsonl & done
    for g in 2 3; do CUDA_VISIBLE_DEVICES=$g python generate_reasoning_traces.py \
        --gpu_id $g --num_shards 4 --source orca_math --model_dir /path/to/QwQ-32B \
        --output /tmp/traces_$g.jsonl & done
    wait; cat /tmp/traces_*.jsonl > /path/to/qwq_reasoning_traces.jsonl
"""

import argparse
import json

import torch
from datasets import load_dataset
from transformers import AutoModelForCausalLM, AutoTokenizer

# Few-shot GSM8K-style exemplars to elicit "#### <answer>" chain-of-thought.
# These are *exemplars only*; no GSM8K train/test data is used as questions, so
# downstream GSM8K evaluation stays fair.
FEW_SHOT_EXAMPLES = [
    {
        "q": "There are 15 trees in the grove. Grove workers will plant trees in the grove today. After they are done, there will be 21 trees. How many trees did the grove workers plant today?",
        "a": "There are 15 trees originally. Then there were 21 trees after some more were planted. So there must have been 21 - 15 = 6. #### 6",
    },
    {
        "q": "If there are 3 cars in the parking lot and 2 more cars arrive, how many cars are in the parking lot?",
        "a": "There are originally 3 cars. 2 more cars arrive. 3 + 2 = 5. #### 5",
    },
    {
        "q": "Leah had 32 chocolates and her sister had 42. If they ate 35, how many pieces do they have left in total?",
        "a": "Originally, Leah had 32 chocolates. Her sister had 42. So in total they had 32 + 42 = 74. After eating 35, they had 74 - 35 = 39. #### 39",
    },
    {
        "q": "Jason had 20 lollipops. He gave Denny some lollipops. Now Jason has 12 lollipops. How many lollipops did Jason give to Denny?",
        "a": "Jason started with 20 lollipops. Then he had 12 after giving some to Denny. So he gave Denny 20 - 12 = 8. #### 8",
    },
    {
        "q": "Shawn has five toys. For Christmas, he got two toys each from his mom and dad. How many toys does he have now?",
        "a": "Shawn started with 5 toys. If he got 2 toys each from mom and dad, then that is 2 + 2 = 4 more toys. 5 + 4 = 9. #### 9",
    },
]

SOURCES = {
    "openmath": ("nvidia/OpenMathInstruct-2", "problem", True),  # (hf_id, field, streaming)
    "orca_math": ("microsoft/orca-math-word-problems-200k", "question", False),
}


def build_prompt(question: str) -> str:
    prompt = ""
    for ex in FEW_SHOT_EXAMPLES:
        prompt += f"Question: {ex['q']}\nAnswer: {ex['a']}\n\n"
    prompt += f"Question: {question}\nAnswer:"
    return prompt


def load_questions(source: str, max_per_source: int) -> list[str]:
    hf_id, field, streaming = SOURCES[source]
    ds = load_dataset(hf_id, split="train", streaming=streaming)
    questions: list[str] = []
    for ex in ds:
        if len(questions) >= max_per_source:
            break
        q = (ex.get(field, "") or "").strip()
        if q and len(q) > 10:
            questions.append(q)
    return questions


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--model_dir", required=True, help="HF causal LM teacher (e.g. Phi-4, QwQ-32B).")
    ap.add_argument("--output", required=True, help="Output JSONL path for this shard.")
    ap.add_argument("--source", choices=sorted(SOURCES.keys()), required=True)
    ap.add_argument("--max_per_source", type=int, default=5000)
    ap.add_argument("--gpu_id", type=int, default=0, help="Shard index (also used to slice questions).")
    ap.add_argument("--num_shards", type=int, default=1, help="Total shards across all sources.")
    ap.add_argument("--max_new_tokens", type=int, default=512)
    ap.add_argument("--batch_size", type=int, default=4)
    ap.add_argument("--device", default="cuda:0")
    args = ap.parse_args()

    # Slice the source's questions for this shard. num_shards covers BOTH sources,
    # so each source is split into num_shards/2 slices (>=1).
    slices_per_source = max(1, args.num_shards // len(SOURCES))
    shard_size = max(1, args.max_per_source // slices_per_source)
    slice_idx = args.gpu_id % slices_per_source
    start, end = slice_idx * shard_size, slice_idx * shard_size + shard_size

    print(f"[gpu {args.gpu_id}] model={args.model_dir} source={args.source} slice[{start}:{end}] -> {args.output}")

    tok = AutoTokenizer.from_pretrained(args.model_dir, trust_remote_code=True)
    if tok.pad_token is None:
        tok.pad_token = tok.eos_token
    tok.padding_side = "left"
    model = AutoModelForCausalLM.from_pretrained(
        args.model_dir, torch_dtype=torch.bfloat16, device_map=args.device, trust_remote_code=True
    ).eval()

    questions = load_questions(args.source, args.max_per_source)[start:end]
    print(f"[gpu {args.gpu_id}] generating traces for {len(questions)} questions...")

    results = []
    for s in range(0, len(questions), args.batch_size):
        batch_qs = questions[s : s + args.batch_size]
        inputs = tok(
            [build_prompt(q) for q in batch_qs], return_tensors="pt", padding=True, truncation=True, max_length=2048
        )
        inputs = {k: v.to(model.device) for k, v in inputs.items()}
        with torch.no_grad():
            out = model.generate(
                **inputs,
                max_new_tokens=args.max_new_tokens,
                do_sample=False,
                eos_token_id=tok.eos_token_id,
                pad_token_id=tok.pad_token_id,
            )
        plen = inputs["input_ids"].shape[1]
        for q, o in zip(batch_qs, out, strict=False):
            gen = tok.decode(o[plen:], skip_special_tokens=True).strip()
            results.append(
                {
                    "messages": [
                        {"role": "user", "content": q},
                        {"role": "assistant", "content": gen},
                    ],
                    "source": "generated",
                    "source_dataset": args.source,
                }
            )
        done = min(s + args.batch_size, len(questions))
        if done % 200 == 0 or done >= len(questions):
            print(f"  [gpu {args.gpu_id}] {done}/{len(questions)}")

    with open(args.output, "w") as f:
        for r in results:
            f.write(json.dumps(r) + "\n")

    has_ans = sum(1 for r in results if "####" in r["messages"][1]["content"])
    print(f"[gpu {args.gpu_id}] DONE: {len(results)} traces ({has_ans} with #### markers) -> {args.output}")


if __name__ == "__main__":
    main()
