#
# Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT
#

#!/usr/bin/env python3
"""Step 5: validate a subgraph_partition.json against an ONNX model.

Checks performed
----------------
0  num_subgraphs must equal len(subgraphs) when present.
1  Empty node names — unnamed nodes (auto-generated by some exporters) are
   never matched by BFS and will silently produce empty subgraphs.
2  Node existence — the name must belong to a *graph node* (has an op_type).
   Referencing an initializer or graph-input name by mistake is caught here.
3  No Constant/ConstantOfShape or Q/DQ wrapper as boundary — these are shape
   side-branches or quantization wrappers, not architectural anchors.  BFS
   from a compute node (Conv/MatMul/Add/…) captures surrounding Q/DQ nodes
   automatically.
4  Closure — every end_node must be reachable from start_nodes by BFS.  An
   unclosed subgraph silently resolves to fewer nodes than intended.
5  Size sanity (>25 % of total nodes) — signals a residual-fork BFS explosion
   in both float and quantized models.  When a node visited before the end
   node fans out to an external consumer (e.g. a residual skip), BFS cascades
   through the rest of the model.  Fix: move end_node back to the last node
   whose output has no external consumers.

Usage:
    python3 validate_partition.py <model.onnx> <subgraph_partition.json>
"""

import json
import sys
from collections import deque

import onnx

QDQ_OPS = {
    "QuantizeLinear",
    "DequantizeLinear",
    "ExtendedQuantizeLinear",
    "ExtendedDequantizeLinear",
    "BFPQuantizeDequantize",
    "MXQuantizeDequantize",
}


def validate(model_path: str, json_path: str) -> list[str]:
    model = onnx.load(model_path)
    with open(json_path) as f:
        data = json.load(f)

    node_map = {n.name: n for n in model.graph.node}
    init_names = {i.name for i in model.graph.initializer}
    inp_names = {i.name for i in model.graph.input}
    in_to_nodes: dict = {}
    for n in model.graph.node:
        for inp in n.input:
            in_to_nodes.setdefault(inp, []).append(n.name)

    def _infer_quantized() -> bool:
        for sg in data["subgraphs"]:
            starts = [n for n in sg["start_nodes"] if n in node_map]
            ends = set(sg["end_nodes"]) & node_map.keys()
            visited, q = set(), deque(starts)
            while q:
                cur = q.popleft()
                if cur in visited or cur not in node_map:
                    continue
                visited.add(cur)
                if node_map[cur].op_type in QDQ_OPS:
                    return True
                if cur in ends:
                    continue
                for out in node_map[cur].output:
                    for nxt in in_to_nodes.get(out, []):
                        if nxt not in visited:
                            q.append(nxt)
        return False

    if "quantized" not in data:
        data["quantized"] = _infer_quantized()

    # Check 0
    actual_count = len(data["subgraphs"])
    errors: list[str] = []
    if "num_subgraphs" in data and data["num_subgraphs"] != actual_count:
        errors.append(
            f"num_subgraphs={data['num_subgraphs']} but subgraphs array has "
            f"{actual_count} entries — set num_subgraphs={actual_count}"
        )
    data["num_subgraphs"] = actual_count

    for sg in data["subgraphs"]:
        name = sg["name"]
        for field in ("start_nodes", "end_nodes"):
            for node_name in sg[field]:
                # Check 1
                if not node_name:
                    errors.append(f"[{name}/{field}] empty node name")
                    continue
                # Check 2
                if node_name not in node_map:
                    if node_name in init_names:
                        errors.append(f"[{name}/{field}] '{node_name}' is an INITIALIZER not a graph node")
                    elif node_name in inp_names:
                        errors.append(f"[{name}/{field}] '{node_name}' is a GRAPH INPUT not a graph node")
                    else:
                        errors.append(f"[{name}/{field}] '{node_name}' not found")
                    continue
                # Check 3
                op = node_map[node_name].op_type
                if op in ("Constant", "ConstantOfShape"):
                    consumers = [
                        (c, node_map[c].op_type)
                        for out in node_map[node_name].output
                        for c in in_to_nodes.get(out, [])
                        if c in node_map
                    ]
                    errors.append(
                        f"[{name}/{field}] '{node_name}' has op={op} "
                        f"(shape side-branch). Feeds: {consumers}. Use the data-path node instead."
                    )
                elif op in QDQ_OPS:
                    errors.append(
                        f"[{name}/{field}] '{node_name}' has op={op} "
                        f"(Q/DQ wrapper). Use the adjacent compute node (Conv/MatMul/Add/…) instead."
                    )

        # Check 4: closure
        starts = [n for n in sg["start_nodes"] if n in node_map]
        ends = set(sg["end_nodes"]) & node_map.keys()
        visited: set = set()
        q: deque = deque(starts)
        while q:
            cur = q.popleft()
            if cur in visited or cur not in node_map:
                continue
            visited.add(cur)
            if cur in ends:
                continue
            for out in node_map[cur].output:
                for nxt in in_to_nodes.get(out, []):
                    if nxt not in visited:
                        q.append(nxt)
        unreached = ends - visited
        if unreached:
            errors.append(f"[{name}] end_nodes not reachable from start_nodes: {unreached}")

        # Check 5: size sanity
        total_nodes = len(node_map)
        pct = 100.0 * len(visited) / total_nodes if total_nodes else 0
        if pct > 25:
            suspects = []
            for vnode in visited:
                if vnode not in node_map:
                    continue
                for vout in node_map[vnode].output:
                    consumers = in_to_nodes.get(vout, [])
                    external = [c for c in consumers if c not in visited and c in node_map]
                    if external and any(c in visited for c in consumers):
                        suspects.append(
                            f"'{vnode}' (op={node_map[vnode].op_type}) fans out to "
                            f"external {external} — try end_node='{vnode}'"
                        )
            hint = (
                "; ".join(suspects[:3]) + (" …" if len(suspects) > 3 else "")
                if suspects
                else "inspect visited nodes for fan-out to external consumers"
            )
            errors.append(
                f"[{name}] resolves to {len(visited)}/{total_nodes} nodes ({pct:.0f}%) — "
                f"likely residual-fork BFS explosion. {hint}."
            )

    return errors


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <model.onnx> <subgraph_partition.json>", file=sys.stderr)
        sys.exit(1)
    errs = validate(sys.argv[1], sys.argv[2])
    for e in errs:
        print("ERROR:", e)
    if not errs:
        print("All checks passed.")
