#
# Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT
#
"""Quark Quant-Perf-owned Git worktrees for framework and kernel optimization.

The user-provided repository is treated as an immutable source.  All framework
fixes and retained kernel patches land in a persistent integration worktree;
each GEAK attempt gets a disposable detached candidate worktree.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
from collections.abc import Iterator
from contextlib import ExitStack, contextmanager, suppress
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from quark.experimental.torch.quant_perf.session.spec import Checkpoint
from quark.experimental.torch.quant_perf.workspace.source_tree import is_runtime_generated_change


class WorkspaceError(RuntimeError):
    pass


_HIPIFY_GENERATED_BREADCRUMB = b"// !!! This is a file automatically generated by hipify!!!"


@dataclass(frozen=True)
class RepoWorkspace:
    role: str
    source_repo: Path
    integration_path: Path
    original_branch: str
    work_branch: str
    base_sha: str


@dataclass(frozen=True)
class CandidateWorkspace:
    role: str
    path: Path
    base_sha: str
    candidate_id: str = ""
    intent: str = "optimization"


@dataclass(frozen=True)
class ChangeTransaction:
    intent: str
    candidate_id: str
    workspaces: dict[str, CandidateWorkspace]


def _slug(value: str, limit: int = 48) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9._-]+", "-", value).strip("-._")
    return (cleaned or "workspace")[:limit]


class RepoWorkspaceManager:
    def __init__(
        self,
        *,
        session_dir: str | Path,
        session_id: str,
        ckpt: Checkpoint,
        root_dir: str | Path | None = None,
        init_submodules: bool = True,
    ) -> None:
        self.session_dir = Path(session_dir).resolve()
        self.session_id = session_id
        self.ckpt = ckpt
        self.root_dir = Path(root_dir or Path("/tmp/quark_quant_perf_worktrees") / session_id).resolve()
        self.init_submodules = init_submodules
        self.ckpt.state.setdefault("repo_workspaces", {})
        self.ckpt.state.setdefault("transient_resources", [])
        self.ckpt.state.setdefault("cleanup", {"status": "pending", "removed": [], "errors": []})

    @staticmethod
    def _git(repo: Path, *args: str, check: bool = True) -> str:
        result = subprocess.run(
            ["git", *args],
            cwd=repo,
            capture_output=True,
            text=True,
        )
        if check and result.returncode != 0:
            raise WorkspaceError(f"git {' '.join(args)} failed in {repo}: {(result.stderr or result.stdout).strip()}")
        return result.stdout.strip()

    def _save(self) -> None:
        if self.ckpt is not None:
            self.ckpt.save()

    def _marker(
        self,
        path: Path,
        resource_type: str,
        **fields: Any,
    ) -> None:
        path.mkdir(parents=True, exist_ok=True)
        data = {
            "session_id": self.session_id,
            "resource_type": resource_type,
            "worktree_path": str(path),
            **fields,
        }
        (path.parent / ".quark-quant-perf-owned.json").write_text(json.dumps(data, indent=2))

    def _validate_owned(
        self,
        path: Path,
        resource_type: str,
    ) -> dict[str, Any]:
        path = path.resolve()
        try:
            path.relative_to(self.root_dir)
        except ValueError as exc:
            raise WorkspaceError(f"refusing to remove path outside Quark Quant-Perf root: {path}") from exc
        marker = path.parent / ".quark-quant-perf-owned.json"
        if not marker.is_file():
            raise WorkspaceError(f"ownership marker missing: {marker}")
        data = json.loads(marker.read_text())
        if data.get("session_id") != self.session_id:
            raise WorkspaceError(f"ownership session mismatch for {path}")
        if data.get("resource_type") != resource_type:
            raise WorkspaceError(f"ownership resource mismatch for {path}")
        if Path(data.get("worktree_path", "")).resolve() != path:
            raise WorkspaceError(f"ownership path mismatch for {path}")
        return data

    @staticmethod
    def _refresh_marker_owner(path: Path) -> None:
        marker = path.parent / ".quark-quant-perf-owned.json"
        data = json.loads(marker.read_text())
        data["owner_pid"] = os.getpid()
        marker.write_text(json.dumps(data, indent=2))

    def _init_submodules(self, worktree: Path) -> None:
        if not self.init_submodules:
            return
        if not (worktree / ".gitmodules").is_file():
            return
        self._git(worktree, "submodule", "update", "--init", "--recursive")

    def _record_for(self, role: str) -> dict[str, Any] | None:
        value = self.ckpt.state["repo_workspaces"].get(role)
        return dict(value) if value else None

    @staticmethod
    def _pid_is_alive(pid: int) -> bool:
        if pid <= 0:
            return False
        try:
            os.kill(pid, 0)
        except ProcessLookupError:
            return False
        except PermissionError:
            return True
        return True

    def _reclaim_stale_candidate(
        self,
        source_repo: Path,
        path: Path,
    ) -> None:
        marker = self._validate_owned(path, "candidate_worktree")
        owner_pid = int(marker.get("owner_pid") or 0)
        if self._pid_is_alive(owner_pid):
            raise WorkspaceError(f"candidate worktree has active owner pid={owner_pid}: {path}")
        self._remove_worktree(
            source_repo,
            path,
            "candidate_worktree",
        )
        self.ckpt.state["transient_resources"] = [
            item for item in self.ckpt.state["transient_resources"] if item.get("path") != str(path)
        ]
        self._save()

    def _worktree_changes(self, worktree: Path) -> list[str]:
        status = self._git(
            worktree,
            "status",
            "--porcelain",
            "--untracked-files=all",
            "--ignore-submodules=dirty",
        )
        return [
            line
            for line in status.splitlines()
            if line[3:] != ".quark-quant-perf-owned.json"
            and not (line.startswith("?? ") and line[3:].startswith(".codex/"))
            and not self._is_hipify_generated_artifact(worktree, line)
            and not self._is_runtime_generated_artifact(line)
        ]

    @staticmethod
    def _is_runtime_generated_artifact(status_line: str) -> bool:
        if not status_line.startswith("?? "):
            return False
        return is_runtime_generated_change(status_line[3:])

    @staticmethod
    def _is_hipify_generated_artifact(worktree: Path, status_line: str) -> bool:
        if not status_line.startswith("?? "):
            return False
        relative_path = status_line[3:]
        path = worktree / relative_path
        if path.is_symlink() or not path.is_file():
            return False
        try:
            with path.open("rb") as stream:
                return stream.readline().rstrip() == _HIPIFY_GENERATED_BREADCRUMB
        except OSError:
            return False

    @staticmethod
    def _from_record(
        role: str,
        record: dict[str, Any],
    ) -> RepoWorkspace:
        return RepoWorkspace(
            role=role,
            source_repo=Path(record["source_repo"]),
            integration_path=Path(record["integration_path"]),
            original_branch=record["original_branch"],
            work_branch=record["work_branch"],
            base_sha=record["base_sha"],
        )

    def _ensure_integration(
        self,
        role: str,
        record: dict[str, Any],
    ) -> RepoWorkspace:
        workspace = self._from_record(role, record)
        if workspace.integration_path.is_dir():
            self._validate_owned(workspace.integration_path, "integration_worktree")
            if (workspace.integration_path / ".git").is_file():
                self._refresh_marker_owner(workspace.integration_path)
                return workspace
            shutil.rmtree(workspace.integration_path)
            self._git(
                workspace.source_repo,
                "worktree",
                "prune",
                check=False,
            )
        workspace.integration_path.parent.mkdir(parents=True, exist_ok=True)
        branch_exists = self._git(
            workspace.source_repo,
            "show-ref",
            "--verify",
            f"refs/heads/{workspace.work_branch}",
            check=False,
        )
        branch_created = not bool(branch_exists)
        if branch_created:
            self._git(
                workspace.source_repo,
                "branch",
                workspace.work_branch,
                workspace.base_sha,
            )
        try:
            self._git(
                workspace.source_repo,
                "worktree",
                "add",
                str(workspace.integration_path),
                workspace.work_branch,
            )
        except Exception:
            if branch_created:
                self._git(
                    workspace.source_repo,
                    "branch",
                    "-D",
                    workspace.work_branch,
                    check=False,
                )
            raise
        self._marker(
            workspace.integration_path,
            "integration_worktree",
            source_repo=str(workspace.source_repo),
            role=role,
            work_branch=workspace.work_branch,
            base_sha=workspace.base_sha,
            owner_pid=os.getpid(),
        )
        self._init_submodules(workspace.integration_path)
        record["status"] = "active"
        record["final_sha"] = ""
        record["branch_retained"] = False
        self.ckpt.state["repo_workspaces"][role] = record
        self.ckpt.state["cleanup"] = {
            "status": "pending",
            "removed": [],
            "errors": [],
        }
        self._save()
        return workspace

    def prepare(self, role: str, source_repo: str | Path) -> RepoWorkspace:
        source = Path(source_repo).resolve()
        if not source.is_dir():
            raise WorkspaceError(f"repository does not exist: {source}")

        existing = self._record_for(role)
        if existing:
            if Path(existing["source_repo"]).resolve() != source:
                raise WorkspaceError(f"{role} repository changed across resume: {existing['source_repo']} -> {source}")
            return self._ensure_integration(role, existing)

        for other_role, other in self.ckpt.state["repo_workspaces"].items():
            if Path(other["source_repo"]).resolve() != source:
                continue
            shared = dict(other)
            shared["shared_with"] = other_role
            self.ckpt.state["repo_workspaces"][role] = shared
            self._save()
            return self._ensure_integration(role, shared)

        dirty = self._worktree_changes(source)
        if dirty:
            raise WorkspaceError(f"repository is dirty; commit or clean it before Quark Quant-Perf: {source}")

        original_branch = self._git(source, "branch", "--show-current")
        base_sha = self._git(source, "rev-parse", "HEAD")
        prefix = _slug(self.session_id.split("-", 1)[0], 24)
        work_branch = f"quark-quant-perf-{prefix}"
        branch_exists = self._git(
            source,
            "show-ref",
            "--verify",
            f"refs/heads/{work_branch}",
            check=False,
        )
        if branch_exists:
            raise WorkspaceError(f"work branch already exists without checkpoint state: {work_branch}")
        self._git(source, "branch", work_branch, base_sha)

        integration = self.root_dir / role / "integration" / "worktree"
        integration.parent.mkdir(parents=True, exist_ok=True)
        try:
            self._git(source, "worktree", "add", str(integration), work_branch)
            self._marker(
                integration,
                "integration_worktree",
                source_repo=str(source),
                role=role,
                work_branch=work_branch,
                base_sha=base_sha,
                owner_pid=os.getpid(),
            )
            self._init_submodules(integration)
        except Exception:
            if (integration.parent / ".quark-quant-perf-owned.json").is_file():
                self._remove_worktree(source, integration, "integration_worktree")
            else:
                self._git(
                    source,
                    "worktree",
                    "remove",
                    "--force",
                    str(integration),
                    check=False,
                )
                self._prune_empty_dirs(integration.parent)
            self._git(source, "branch", "-D", work_branch, check=False)
            raise

        record = {
            "source_repo": str(source),
            "integration_path": str(integration),
            "original_branch": original_branch,
            "work_branch": work_branch,
            "base_sha": base_sha,
            "final_sha": "",
            "status": "active",
        }
        self.ckpt.state["repo_workspaces"][role] = record
        self._save()
        return self._from_record(role, record)

    @contextmanager
    def execution_worktree(
        self,
        role: str,
        source_repo: str | Path,
        execution_id: str,
    ) -> Iterator[Path]:
        source = Path(source_repo).resolve()
        if not source.is_dir():
            raise WorkspaceError(f"repository does not exist: {source}")
        base_sha = self._git(source, "rev-parse", "HEAD")
        path = self.root_dir / role / "executions" / _slug(execution_id) / "worktree"
        if path.exists():
            self._remove_worktree(
                source,
                path,
                "execution_worktree",
            )
        path.parent.mkdir(parents=True, exist_ok=True)
        self._git(
            source,
            "worktree",
            "add",
            "--detach",
            str(path),
            base_sha,
        )
        resource = {
            "resource_type": "execution_worktree",
            "role": role,
            "execution_id": execution_id,
            "source_repo": str(source),
            "path": str(path),
            "owner_pid": os.getpid(),
            "status": "active",
        }
        try:
            self._marker(
                path,
                "execution_worktree",
                source_repo=str(source),
                role=role,
                execution_id=execution_id,
                base_sha=base_sha,
                owner_pid=os.getpid(),
            )
            self.ckpt.state["transient_resources"].append(resource)
            self._save()
            yield path
        finally:
            try:
                self._remove_worktree(
                    source,
                    path,
                    "execution_worktree",
                )
            finally:
                self.ckpt.state["transient_resources"] = [
                    item for item in self.ckpt.state["transient_resources"] if item.get("path") != str(path)
                ]
                self._save()

    @contextmanager
    def candidate(
        self,
        role: str,
        candidate_id: str,
        *,
        intent: str = "optimization",
    ) -> Iterator[CandidateWorkspace]:
        record = self._record_for(role)
        if not record:
            raise WorkspaceError(f"{role} integration worktree is not prepared")
        integration = self._ensure_integration(role, record)
        dirty = self._worktree_changes(integration.integration_path)
        if dirty:
            raise WorkspaceError(f"integration worktree is dirty before GEAK: {integration.integration_path}")
        base_sha = self._git(integration.integration_path, "rev-parse", "HEAD")
        path = self.root_dir / role / "candidates" / _slug(candidate_id) / "worktree"
        if path.exists():
            self._reclaim_stale_candidate(
                integration.source_repo,
                path,
            )
        path.parent.mkdir(parents=True, exist_ok=True)
        self._git(
            integration.source_repo,
            "worktree",
            "add",
            "--detach",
            str(path),
            base_sha,
        )
        try:
            self._marker(
                path,
                "candidate_worktree",
                source_repo=str(integration.source_repo),
                role=role,
                candidate_id=candidate_id,
                kernel_id=candidate_id,
                intent=intent,
                base_sha=base_sha,
                owner_pid=os.getpid(),
            )
            self._init_submodules(path)
            resource = {
                "resource_type": "candidate_worktree",
                "role": role,
                "candidate_id": candidate_id,
                "kernel_id": candidate_id,
                "intent": intent,
                "path": str(path),
                "owner_pid": os.getpid(),
                "status": "active",
            }
            self.ckpt.state["transient_resources"].append(resource)
            self._save()
        except Exception:
            if (path.parent / ".quark-quant-perf-owned.json").is_file():
                self._remove_worktree(integration.source_repo, path, "candidate_worktree")
            else:
                self._git(
                    integration.source_repo,
                    "worktree",
                    "remove",
                    "--force",
                    str(path),
                    check=False,
                )
                self._prune_empty_dirs(path.parent)
            raise
        try:
            yield CandidateWorkspace(
                role=role,
                path=path,
                base_sha=base_sha,
                candidate_id=candidate_id,
                intent=intent,
            )
        finally:
            self._remove_worktree(integration.source_repo, path, "candidate_worktree")
            self.ckpt.state["transient_resources"] = [
                item for item in self.ckpt.state["transient_resources"] if item.get("path") != str(path)
            ]
            self._save()

    @contextmanager
    def transaction(
        self,
        *,
        intent: str,
        candidate_id: str,
        roles: tuple[str, ...],
    ) -> Iterator[ChangeTransaction]:
        with ExitStack() as stack:
            workspaces = {
                role: stack.enter_context(
                    self.candidate(
                        role,
                        candidate_id,
                        intent=intent,
                    )
                )
                for role in roles
            }
            yield ChangeTransaction(
                intent=intent,
                candidate_id=candidate_id,
                workspaces=workspaces,
            )

    def promote_candidate(
        self,
        candidate: CandidateWorkspace,
        *,
        message: str,
    ) -> bool:
        record = self._record_for(candidate.role)
        if not record:
            raise WorkspaceError(f"{candidate.role} integration worktree is not prepared")
        integration = self._ensure_integration(candidate.role, record)
        integration_head = self._git(
            integration.integration_path,
            "rev-parse",
            "HEAD",
        )
        if integration_head != candidate.base_sha:
            raise WorkspaceError(
                f"{candidate.role} integration advanced during candidate: {candidate.base_sha} -> {integration_head}"
            )
        diff_result = subprocess.run(
            [
                "git",
                "diff",
                "--binary",
                f"{candidate.base_sha}..HEAD",
            ],
            cwd=candidate.path,
            capture_output=True,
        )
        if diff_result.returncode != 0:
            raise WorkspaceError(f"candidate diff failed: {diff_result.stderr.decode(errors='replace').strip()}")
        diff = diff_result.stdout
        if not diff.strip():
            return False
        result = subprocess.run(
            ["git", "apply", "--index", "-"],
            cwd=integration.integration_path,
            input=diff,
            capture_output=True,
        )
        if result.returncode != 0:
            self._git(
                integration.integration_path,
                "reset",
                "--hard",
                integration_head,
                check=False,
            )
            raise WorkspaceError(
                f"candidate promotion failed: {(result.stderr or result.stdout).decode(errors='replace').strip()}"
            )
        self._git(
            integration.integration_path,
            "commit",
            "-m",
            message,
        )
        return True

    def promote_transaction(
        self,
        transaction: ChangeTransaction,
        *,
        message: str,
    ) -> list[str]:
        original_heads = {
            role: self._git(
                self._ensure_integration(role, self._record_for(role)).integration_path,
                "rev-parse",
                "HEAD",
            )
            for role in transaction.workspaces
        }
        promoted: list[str] = []
        try:
            for role, candidate in transaction.workspaces.items():
                if self.promote_candidate(
                    candidate,
                    message=f"{message} ({role})",
                ):
                    promoted.append(role)
            return promoted
        except Exception:
            for role in promoted:
                record = self._record_for(role)
                if not record:
                    continue
                integration = self._ensure_integration(role, record)
                self._git(
                    integration.integration_path,
                    "reset",
                    "--hard",
                    original_heads[role],
                    check=False,
                )
            raise

    def _remove_worktree(self, source_repo: Path, path: Path, resource_type: str) -> None:
        if not path.exists():
            self._git(source_repo, "worktree", "prune", check=False)
            return
        self._validate_owned(path, resource_type)
        result = subprocess.run(
            ["git", "worktree", "remove", "--force", str(path)],
            cwd=source_repo,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0 and path.exists():
            self._validate_owned(path, resource_type)
            shutil.rmtree(path)
        self._git(source_repo, "worktree", "prune", check=False)
        marker = path.parent / ".quark-quant-perf-owned.json"
        marker.unlink(missing_ok=True)
        with suppress(OSError):
            path.parent.rmdir()
        self._prune_empty_dirs(path.parent.parent)

    def _prune_empty_dirs(self, start: Path) -> None:
        current = start.resolve()
        while True:
            try:
                current.relative_to(self.root_dir)
            except ValueError:
                return
            try:
                current.rmdir()
            except OSError:
                return
            if current == self.root_dir:
                return
            current = current.parent

    def cleanup_terminal(self) -> None:
        cleanup = self.ckpt.state["cleanup"]
        cleanup.update({"status": "running", "removed": [], "errors": []})
        self._save()
        resources = list(self.ckpt.state.get("transient_resources") or [])
        remaining_resources = []
        for index, resource in enumerate(resources):
            path_value = resource.get("path", "")
            role = resource.get("role", "")
            record = self._record_for(role)
            source_repo = str(record.get("source_repo") or "") if record else str(resource.get("source_repo") or "")
            if not path_value or not source_repo:
                remaining_resources.append(resource)
                continue
            path = Path(path_value)
            resource["cleanup_status"] = "removing"
            self._save()
            try:
                self._remove_worktree(
                    Path(source_repo),
                    path,
                    resource.get("resource_type", "candidate_worktree"),
                )
                cleanup["removed"].append(str(path))
            except Exception as exc:
                resource["cleanup_status"] = "failed"
                remaining_resources.append(resource)
                cleanup["errors"].append(f"{type(exc).__name__}: {exc}")
            self.ckpt.state["transient_resources"] = [
                *remaining_resources,
                *resources[index + 1 :],
            ]
            self._save()

        seen: set[Path] = set()
        records = self.ckpt.state["repo_workspaces"]
        for record in records.values():
            path = Path(record["integration_path"])
            if path in seen:
                continue
            seen.add(path)
            source = Path(record["source_repo"])
            try:
                if path.exists() and self._worktree_changes(path):
                    raise WorkspaceError(f"integration worktree dirty at terminal cleanup: {path}")
                final_sha = (
                    self._git(path, "rev-parse", "HEAD") if path.exists() else str(record.get("final_sha") or "")
                )
                if not final_sha:
                    work_branch = str(record.get("work_branch") or "")
                    if work_branch:
                        final_sha = self._git(
                            source,
                            "rev-parse",
                            work_branch,
                            check=False,
                        )
                if not final_sha:
                    raise WorkspaceError(f"cannot determine final revision for missing integration worktree: {path}")
                final_tree = self._git(source, "rev-parse", f"{final_sha}^{{tree}}")
                base_tree = self._git(source, "rev-parse", f"{record['base_sha']}^{{tree}}")
                branch_retained = final_tree != base_tree
                shared_records = [shared for shared in records.values() if Path(shared["integration_path"]) == path]
                for shared in shared_records:
                    shared["final_sha"] = final_sha
                    shared["branch_retained"] = branch_retained
                    shared["status"] = "removing"
                self._save()
                self._remove_worktree(source, path, "integration_worktree")
                if not branch_retained:
                    self._git(
                        source,
                        "branch",
                        "-D",
                        record["work_branch"],
                        check=False,
                    )
                for shared in shared_records:
                    shared["status"] = "removed"
                cleanup["removed"].append(str(path))
                self._save()
            except Exception as exc:  # cleanup must not hide the run result
                cleanup["errors"].append(f"{type(exc).__name__}: {exc}")
                self._save()
        cleanup["status"] = "failed" if cleanup["errors"] else "complete"
        self._save()
